tests/nimble_l2cap: adjust buffer sizes for nrf51
aabadie/RIOT pull request #13
Opened 2019-08-05 12:43 UTC by haukepetersen

Enabling the `ble_nimble` feature for nrf51 boards will most likely let `tests/nimble_l2cap` fail due to missing RAM on those boards. This PR adds a crude enhancement to the test application, to limit the used buffers for those boards. Its not pretty, but should do the job for now...

2019-08-05 12:57 UTC, aabadie requested changes
I fine with the proposed change but does it work with these low values ? If not I would just simply blacklist the boards.

2019-08-05 12:57 UTC, aabadie commented on tests/nimble_l2cap_server/nimble.inc.mk
> +NRF51_WL := airfy-beacon calliope-mini microbit nrf51dk nrf51dongle nrf6310 \
Maybe rename the variable `BOARDS_NRF51` ?

2019-08-07 07:32 UTC, haukepetersen commented
> I fine with the proposed change but does it work with these low values ?

Yes, the test also works with these lower value. Of course its not that much of a stress test, but flooding 500 byte packets on a l2cap channel is still something useful.

2019-08-07 07:36 UTC, haukepetersen commented
applied the variable change and squashed.

2019-08-07 07:53 UTC, aabadie commented
Your branch is conflicting with my base branch so I directly cherry-picked your commit instead of merging.

2019-08-07 07:53 UTC, closed without merging